### ISSUE TITLE
Problem on Mac OS X Yosemite 10.10.5 (Bitalino PX-0200-001865)

### ISSUE THREAD

**Issue by faturita** [BITalinoWorld/python-api#5]
Dear friends from Bitalino,

I am having a very weird problem on OS X Yosemite with current version of python-api.  The call to version(), which calls socket.read(1), or any read operation is completely blocked without returning any value, and if the timeout is set, it timeouts all the time and never returns anything.

Althought accessing the Serial device directly and sending 

`serial.write([0x05])`

which should be the command to instruct the device to start sending data, does produce a change on the device (blink faster), any further serial.read call returns nothing at all.

Opensignal does the same thing.  I can pair the device, it appears on the scanner, but when I start to retrieve information, it gets stuck and it cancel with the same error message: "The computer lost communication with the device"

```
>>> from bitalino import BITalino
>>> a = BITalino('/dev/tty.bitalino-DevB',10)
>>> 
>>> 
>>> a.version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bitalino.py", line 469, in version
    version_str += self.receive(1)
  File "bitalino.py", line 493, in receive
    raise Exception(ExceptionCode.CONTACTING_DEVICE)
Exception: The computer lost communication with the device.
```

Any help or hint will help a lot !!

Thanks!

**Comment by PGFGoncalves** [comment]
Hi Rodrigo,

That is indeed a weird problem. All that you describe indicates that the socket in not receiving anything from the device. However, as you said yourself, it is able to send commands. 
Let me know if you can solve the issue with any, and which, of these possible solutions:
- Remove the BITalino and pair it again.
- Ask for a different serial port outgoing to the device and try it.

Lastly, it does work on another computer, correct?

Best Regards and Good Luck ;)

**Comment by faturita** [comment]
Dear Bitalino Wizard ;)

Thank you very much !!! It was finally a serial port issue on Mac, as you mention.  Mac generates many /dev/cu... ports and you have to select the right one in order to be able to receive data from the device (/dev/cu.bitalino-DevB-1).

Thanks a lot!!!

**Comment by faturita** [comment]
Dear Bitalino Wizard ;)

Yep, it works on linux:

Version:BITalino_v3.3a_18032014
[[  0.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   3.19000000e+02]
..........

Do you know how to change the outgoing serial port on the Mac ?

I will check other bluetooth options to see if there is some particular problem with the bluetooth implementation on Mac.

Thanks a lot !!!

**Comment by faturita** [comment]
Dear Bitalino Wizard ;)

Yep, it works on linux:

Version:BITalino_v3.3a_18032014
[[  0.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   3.19000000e+02]
..........

Do you know how to change the outgoing serial port on the Mac ?

I will check other bluetooth options to see if there is some particular problem with the bluetooth implementation on Mac.

Thanks a lot !!!

**Comment by faturita** [comment]
Dear Bitalino Wizard ;)

Yep, it works on linux:

Version:BITalino_v3.3a_18032014
[[  0.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
    1.00000000e+00   0.00000000e+00   3.19000000e+02]
..........

Do you know how to change the outgoing serial port on the Mac ?

I will check other bluetooth options to see if there is some particular problem with the bluetooth implementation on Mac.

Thanks a lot !!!

**Comment by PGFGoncalves** [comment]
Hi Rodrigo,

Good to know it's working :)
Good Luck on your project!

Best Regards,
